name: Build And Deploy
run-name: Deploy ListaDeViaje to AWS S3

on:
  workflow_dispatch: # allow manual trigger
  push:
    tags: ["[1-9].[0-9][0-9]?.[0-9][0-9]?"]
    paths: ["src/default-travel-list.js"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install
        run: npm ci --no-audit --no-fund
      - name: Build
        run: npm run build
      - name: Fix og:image
        run: node ./scripts/fix-og-images.js
      - name: Set AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          mask-aws-account-id: true
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-south-2
      - name: Deploy
        run: |
          aws --version
          aws s3 sync ./dist \
                      s3://jaimeelingeniero.es/lista-de-viaje \
                      --delete
